"""Tests del verificador lockfile↔inventario (scripts/check_third_party_licenses.py).

El test de sincronía real convierte la desincronización silenciosa de
THIRD-PARTY-LICENSES.md en un fallo de suite: corre en cada pytest
local y en los 3 jobs de test de CI. Los tests unitarios cubren ambos parsers
con fixtures sintéticas (sin tocar los archivos reales).
"""

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent / "scripts"))
from check_third_party_licenses import (
    check,
    licenses_doc_packages,
    lockfile_packages,
    normalize,
)


class TestNormalize:
    def test_pep503_collapses_separators_and_case(self):
        assert normalize("Foo_Bar.baz") == "foo-bar-baz"
        assert normalize("antlr4-python3-runtime") == "antlr4-python3-runtime"


class TestLockfileParser:
    SYNTHETIC_LOCK = """\
# This file was autogenerated by uv via the following command:
#    uv pip compile --universal ...
aiofiles==24.1.0 \\
    --hash=sha256:aaaa \\
    --hash=sha256:bbbb
    # via gradio
colorama==0.4.6 ; sys_platform == 'win32' \\
    --hash=sha256:cccc
torch==2.6.0 ; python_full_version < '3.14' \\
    --hash=sha256:dddd
torch==2.12.1 ; python_full_version >= '3.14' \\
    --hash=sha256:eeee
Some_Package.X==1.0 \\
    --hash=sha256:ffff
"""

    def test_extracts_packages_ignoring_hashes_and_comments(self):
        packages = lockfile_packages(self.SYNTHETIC_LOCK)
        assert packages == {"aiofiles", "colorama", "torch", "some-package-x"}

    def test_deduplicates_marker_variants(self):
        # torch aparece dos veces (marcadores por versión de Python): una sola entrada.
        packages = lockfile_packages(self.SYNTHETIC_LOCK)
        assert sum(1 for p in packages if p == "torch") == 1


class TestLicensesDocParser:
    SYNTHETIC_DOC = """\
# Licencias de terceros

## Tabla señuelo (el parser debe ignorarla)

| Componente | Licencia (metadato) |
|-----------|---------------------|
| `certifi` | MPL-2.0 |

## Inventario completo del lockfile

| Paquete | Versión | Licencia (metadato) | Familia |
|---------|---------|---------------------|--------|
| `aiofiles` | 24.1.0 | Apache Software License | Apache-2.0 |
| `Torch` | 2.6.0 | BSD | BSD |

> Nota posterior que cierra la tabla.

| Otra | Tabla |
|------|-------|
| `no-debe-aparecer` | x |
"""

    def test_parses_only_inventory_table(self):
        packages = licenses_doc_packages(self.SYNTHETIC_DOC)
        assert packages == {"aiofiles", "torch"}
        assert "certifi" not in packages
        assert "no-debe-aparecer" not in packages

    def test_missing_inventory_header_raises(self):
        with pytest.raises(ValueError):
            licenses_doc_packages("# Documento sin tabla de inventario\n")


class TestRealSync:
    def test_licenses_doc_in_sync_with_lockfile(self):
        """El inventario legal debe reflejar el lock universal actual."""
        missing, extra = check()
        assert not missing and not extra, (
            "THIRD-PARTY-LICENSES.md desincronizado con requirements-lock.txt.\n"
            f"  Faltan en el inventario: {missing}\n"
            f"  Sobran en el inventario: {extra}\n"
            "Regenera el inventario (ver §Regeneración de THIRD-PARTY-LICENSES.md)."
        )
