#!/usr/bin/env python3
"""
Genera un instalador Inno Setup para tts-sidecar Windows.

Usage:
    python scripts/create_installer_windows.py <onedir_path> [--output <output_dir>]

Example:
    python scripts/create_installer_windows.py dist/tts-sidecar
"""

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from build_utils import get_version, ensure_ico, ensure_build_dependency, INNOSETUP_PIN, INSTALLER_TIMEOUT


def get_inno_setup_path():
    """Encuentra iscc.exe (compilador Inno Setup) en el sistema."""
    candidates = [
        Path(os.environ.get("ProgramFiles(x86)", "C:/Program Files (x86)")) / "Inno Setup 6" / "ISCC.exe",
        Path(os.environ.get("ProgramFiles", "C:/Program Files")) / "Inno Setup 6" / "ISCC.exe",
        Path("C:/ProgramData/chocolatey/bin/iscc.exe"),
    ]
    for candidate in candidates:
        if candidate.exists():
            return str(candidate)

    for dir_path in os.environ.get("PATH", "").split(os.pathsep):
        candidate = Path(dir_path) / "iscc.exe"
        if candidate.exists():
            return str(candidate)

    return None


def generate_iss(source_dir: Path, output_dir: Path, version: str, info_after: Path,
                 license_file: Path = None, icon_file: Path = None) -> str:
    """
    Genera un script .iss mínimo para Inno Setup.

    Usa rutas con backslash al estilo Windows para compatibilidad con ISCC.
    """
    exe_name = "tts-sidecar.exe"
    source_win = str(source_dir.resolve()).replace("/", "\\")
    output_win = str(output_dir.resolve()).replace("/", "\\")
    info_after_win = str(info_after.resolve()).replace("/", "\\")

    # Construye el contenido ISS con concatenación explícita para evitar
    # problemas de escape de backslashes en strings multilínea.
    lines = []
    lines.append("; Inno Setup script for tts-sidecar")
    lines.append("; Generated by scripts/create_installer_windows.py")
    lines.append("")
    lines.append("[Setup]")
    lines.append("AppId={{E8A1B2C3-D4F5-6789-ABCD-EF0123456789}}")
    lines.append("AppName=tts-sidecar")
    lines.append("AppVersion=" + version)
    lines.append("AppPublisher=tts-sidecar")
    # Instalación per-user (sin UAC): perfil del usuario, patrón {localappdata}\Programs
    # convencional (p.ej. VS Code); {userpf} no es constante estándar de Inno Setup.
    lines.append("DefaultDirName={localappdata}\\Programs\\tts-sidecar")
    lines.append("DefaultGroupName=tts-sidecar")
    lines.append("OutputDir=" + output_win)
    # Vocabulario de arquitectura unificado al estilo `uname -m` (x86_64/aarch64),
    # en paridad con los AppImage de Linux (A-03).
    lines.append("OutputBaseFilename=tts-sidecar-" + version + "-x86_64-setup")
    lines.append("WizardStyle=modern")
    lines.append("PrivilegesRequired=lowest")
    lines.append("ArchitecturesAllowed=x64compatible")
    lines.append("ArchitecturesInstallIn64BitMode=x64compatible")
    # Emite el broadcast de cambio de entorno para que el PATH actualizado se propague.
    lines.append("ChangesEnvironment=yes")
    # Compresión con output periódico visible (heartbeat del step de CI): el
    # default lzma2/max de Inno Setup tarda >10 min de silencio sobre el onedir
    # de ~1.6 GB y CircleCI lo mata; lzma/normal + SolidCompression=no comprime
    # por archivo (progreso continuo) en ~3-5 min, y LZMAUseSeparateProcess=yes
    # paraleliza sin bloquear el thread de UI/log (evidencia pipelines #29-#30).
    lines.append("Compression=lzma/normal")
    lines.append("SolidCompression=no")
    lines.append("LZMAUseSeparateProcess=yes")
    # Página informativa mostrada al terminar la instalación: explica la provisión del modelo.
    lines.append("InfoAfterFile=" + info_after_win)
    # Página de licencia (GPL v3) mostrada como paso de aceptación en el asistente.
    if license_file is not None and license_file.exists():
        lines.append("LicenseFile=" + str(license_file.resolve()).replace("/", "\\"))
    # Icono del asistente del instalador (logo del proyecto); se omite si no se generó.
    has_icon = icon_file is not None and icon_file.exists()
    if has_icon:
        lines.append("SetupIconFile=" + str(icon_file.resolve()).replace("/", "\\"))
    lines.append("")
    lines.append("[Files]")
    lines.append("Source: " + source_win + "\\*; DestDir: {app}; Flags: ignoreversion recursesubdirs createallsubdirs")
    if has_icon:
        # Copia el .ico a {app} para que los accesos directos apunten al logo.
        icon_win = str(icon_file.resolve()).replace("/", "\\")
        lines.append("Source: " + icon_win + "; DestDir: {app}; Flags: ignoreversion")
    lines.append("")
    lines.append("[Icons]")
    icon_suffix = "; IconFilename: {app}\\tts-sidecar.ico" if has_icon else ""
    lines.append("Name: {group}\\tts-sidecar; Filename: {app}\\tts-sidecar.exe" + icon_suffix)
    lines.append("Name: {group}\\Uninstall tts-sidecar; Filename: {uninstallexe}")
    lines.append("Name: {autodesktop}\\tts-sidecar; Filename: {app}\\tts-sidecar.exe" + icon_suffix)
    lines.append("")
    lines.append("[Registry]")
    # La entrada de "Aplicaciones y características" la genera Inno Setup
    # automáticamente ({AppId}_is1); no se escribe una clave Uninstall manual.
    # Añade {app} al PATH del usuario (HKCU), sin elevación, solo si no está ya
    # presente (ver NeedsAddPath en [Code]).
    lines.append('Root: HKCU; Subkey: "Environment"; ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}"; Check: NeedsAddPath(ExpandConstant(\'{app}\')); Flags: preservestringtype')
    lines.append("")
    lines.append("[Run]")
    # Checkbox post-instalación: descarga el modelo a la caché de HuggingFace del
    # usuario. Con PrivilegesRequired=lowest no hay elevación, así que
    # runasoriginaluser queda inerte; se conserva por si el usuario fuerza la
    # instalación elevada (el setup seguiría corriendo como el usuario original).
    # Se lanza vía `cmd /k` para que la consola persista al terminar (W-03): si setup
    # falla, el error queda visible en lugar de desaparecer con la ventana — paridad
    # con la Terminal persistente del .command de macOS.
    lines.append('Filename: {cmd}; Parameters: "/k ""{app}\\tts-sidecar.exe"" setup"; Description: "Descargar ahora el modelo de voz (setup)"; Flags: postinstall skipifsilent runasoriginaluser nowait')
    lines.append("")
    lines.append("[Code]")
    lines.append("function NeedsAddPath(Param: string): boolean;")
    lines.append("var")
    lines.append("  OrigPath: string;")
    lines.append("begin")
    lines.append("  if not RegQueryStringValue(HKCU, 'Environment', 'Path', OrigPath)")
    lines.append("  then begin")
    lines.append("    Result := True;")
    lines.append("    exit;")
    lines.append("  end;")
    lines.append("  Result := Pos(';' + Uppercase(Param) + ';', ';' + Uppercase(OrigPath) + ';') = 0;")
    lines.append("end;")
    lines.append("")
    # Reversión del PATH al desinstalar: Inno Setup no deshace modificaciones a
    # valores de registro existentes, así que la entrada {app} se recorta a mano.
    # Se busca ';{app};' sobre el valor envuelto en ';' (case-insensitive, como
    # NeedsAddPath), cubriendo inicio, medio y fin; si no está, no se toca nada.
    lines.append("procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);")
    lines.append("var")
    lines.append("  OrigPath, AppDir: string;")
    lines.append("  P: Integer;")
    lines.append("begin")
    lines.append("  if CurUninstallStep <> usUninstall then")
    lines.append("    exit;")
    lines.append("  if not RegQueryStringValue(HKCU, 'Environment', 'Path', OrigPath)")
    lines.append("  then")
    lines.append("    exit;")
    lines.append("  AppDir := ExpandConstant('{app}');")
    lines.append("  { Posición del match en el valor envuelto en ';' (1-based). }")
    lines.append("  P := Pos(';' + Uppercase(AppDir) + ';', ';' + Uppercase(OrigPath) + ';');")
    lines.append("  if P = 0 then")
    lines.append("    exit;")
    lines.append("  if P = 1 then")
    lines.append("    { Entrada al inicio: recorta 'AppDir;' desde el comienzo. }")
    lines.append("    Delete(OrigPath, 1, Length(AppDir) + 1)")
    lines.append("  else")
    lines.append("    { Entrada en medio o al final: recorta ';AppDir' con su separador previo. }")
    lines.append("    Delete(OrigPath, P - 1, Length(AppDir) + 1);")
    lines.append("  RegWriteExpandStringValue(HKCU, 'Environment', 'Path', OrigPath);")
    lines.append("end;")

    return "\n".join(lines)


def info_after_text() -> str:
    """Contenido de la página InfoAfter del instalador: provisión + oferta GPLv3.

    Muestra al usuario, tras terminar la instalación, cómo descargar el modelo y
    dónde obtener el código fuente bajo GPLv3 (oferta §6d de la licencia: el
    código completo está disponible públicamente en el repositorio). Se mantiene
    como función pura (sin I/O) para poder testear su contenido desde
    tests/test_create_installer_windows.py.
    """
    return (
        "Provisión del modelo de voz\r\n"
        "===========================\r\n\r\n"
        "tts-sidecar ya está instalado, pero el modelo de voz (es-mx-latam, varios\r\n"
        "cientos de MB) NO viene incluido en el instalador: se descarga aparte, una\r\n"
        "sola vez, a la caché de tu usuario.\r\n\r\n"
        "Marca la casilla \"Descargar ahora el modelo de voz (setup)\" para hacerlo\r\n"
        "al terminar, o ejecútalo más tarde desde una terminal con:\r\n\r\n"
        "    tts-sidecar setup\r\n\r\n"
        "Hasta que el modelo esté descargado, los comandos 'speak' y 'daemon start'\r\n"
        "fallarán de inmediato y te recordarán ejecutar 'tts-sidecar setup'.\r\n\r\n"
        "El instalador añadió la carpeta de instalación al PATH de tu usuario, por lo\r\n"
        "que podrás invocar 'tts-sidecar' por nombre en una terminal nueva.\r\n\r\n"
        "Código fuente (GPLv3)\r\n"
        "======================\r\n\r\n"
        "TTS Sidecar se distribuye bajo la GNU General Public License v3 o\r\n"
        "posterior. El código fuente completo está disponible públicamente bajo\r\n"
        "GPLv3 en el repositorio:\r\n\r\n"
        "    https://github.com/CristianRojas-SoftwareEngineer/TTS-Sidecar\r\n\r\n"
        "Si necesitas el código fuente por separado, descárgalo del repositorio o\r\n"
        "solicítalo al autor; el código está disponible públicamente bajo GPLv3.\r\n"
    )


def main():
    parser = argparse.ArgumentParser(
        description="Create tts-sidecar Windows installer via Inno Setup"
    )
    parser.add_argument(
        "onedir",
        type=Path,
        help="Path to the PyInstaller --onedir output folder",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output directory for the installer (default: dist/)",
    )
    args = parser.parse_args()

    source_dir = args.onedir.resolve()
    output_dir = (args.output or source_dir.parent).resolve()

    if not source_dir.exists():
        print(f"ERROR: Source directory not found: {source_dir}", file=sys.stderr)
        sys.exit(1)

    exe_in_source = source_dir / "tts-sidecar.exe"
    if not exe_in_source.exists():
        candidates = list(source_dir.glob("*/tts-sidecar.exe")) + list(source_dir.glob("tts-sidecar.exe"))
        if candidates:
            exe_in_source = candidates[0]
        else:
            print(f"ERROR: Could not find tts-sidecar.exe in {source_dir}", file=sys.stderr)
            sys.exit(1)

    version = get_version()
    print(f"Version: {version}")
    print(f"Source: {source_dir}")
    print(f"Output: {output_dir}")

    # Inno Setup es la herramienta que genera el instalador: su ausencia o su
    # fallo abortan el build (sys.exit(1) fatal, tanto en CI como localmente),
    # porque un build sin instalador no debe reportar éxito. Se ofrece instalarlo
    # vía Chocolatey pineado si choco existe.
    resolved = ensure_build_dependency(
        "Inno Setup (iscc.exe)",
        lambda: get_inno_setup_path() is not None,
        install_cmd=(
            ["choco", "install", "innosetup", "-y", f"--version={INNOSETUP_PIN}"]
            if shutil.which("choco") else None
        ),
        required=False,
    )
    if not resolved:
        print("ERROR: Inno Setup (iscc.exe) not found.", file=sys.stderr)
        print("Install Inno Setup 6 from: https://jrsoftware.org/isdl.php", file=sys.stderr)
        print(f"Or via Chocolatey: choco install innosetup -y --version={INNOSETUP_PIN}", file=sys.stderr)
        sys.exit(1)
    iscc = get_inno_setup_path()
    print(f"ISCC: {iscc}")

    output_dir.mkdir(parents=True, exist_ok=True)

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".txt", delete=False, encoding="utf-8"
    ) as info_f:
        info_after_path = Path(info_f.name)
        info_f.write(info_after_text())

    # Genera el .ico del logo (degradación con gracia: None si Pillow o la fuente
    # faltan, en cuyo caso el .iss se emite sin líneas de icono).
    icon_dir = Path(tempfile.mkdtemp(prefix="tts-icon-"))
    icon_file = ensure_ico(icon_dir)

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".iss", delete=False, encoding="utf-8"
    ) as f:
        iss_path = Path(f.name)
        license_file = Path(__file__).parent.parent / "LICENSE"
        f.write(generate_iss(source_dir, output_dir, version, info_after_path,
                             license_file, icon_file))

    try:
        print("Compilando instalador con Inno Setup...")
        # Consola heredada (sin capture_output): el progreso por archivo de ISCC
        # es el heartbeat del step de CI. INSTALLER_TIMEOUT holgado con
        # TimeoutExpired atrapado, y el exit code de ISCC se propaga siempre.
        try:
            result = subprocess.run(
                [iscc, str(iss_path)],
                timeout=INSTALLER_TIMEOUT,
            )
        except subprocess.TimeoutExpired:
            print(f"ERROR: Inno Setup excedió {INSTALLER_TIMEOUT}s", file=sys.stderr)
            sys.exit(1)
        if result.returncode != 0:
            print(f"ERROR: Inno Setup failed (exit {result.returncode})", file=sys.stderr)
            sys.exit(1)

        installer_name = f"tts-sidecar-{version}-x86_64-setup.exe"
        installer_path = output_dir / installer_name

        if installer_path.exists():
            size_mb = installer_path.stat().st_size / 1024 / 1024
            print(f"Installer created: {installer_path}")
            print(f"Size: {size_mb:.1f} MB")
        else:
            candidates = list(output_dir.glob("tts-sidecar-*-x86_64-setup.exe"))
            if candidates:
                p = candidates[0]
                size_mb = p.stat().st_size / 1024 / 1024
                print(f"Installer created: {p}")
                print(f"Size: {size_mb:.1f} MB")
            else:
                print("WARNING: Installer file not found in output dir.", file=sys.stderr)

    finally:
        for tmp in (iss_path, info_after_path):
            try:
                tmp.unlink()
            except OSError:
                pass
        try:
            shutil.rmtree(icon_dir)
        except OSError:
            pass


if __name__ == "__main__":
    main()
