#!/usr/bin/env python3
"""
Genera un instalador Inno Setup para tts-sidecar Windows.

Usage:
    python scripts/create_installer_windows.py <onedir_path> [--output <output_dir>]

Example:
    python scripts/create_installer_windows.py dist/tts-sidecar
"""

import argparse
import os
import subprocess
import sys
import tempfile
from pathlib import Path


def get_version():
    """Read version from src/chatterbox_tts/__init__.py."""
    project_root = Path(__file__).parent.parent
    init_path = project_root / "src" / "chatterbox_tts" / "__init__.py"
    content = init_path.read_text(encoding="utf-8")
    for line in content.splitlines():
        line = line.strip()
        if line.startswith("__version__"):
            parts = line.split("=", 1)
            if len(parts) == 2:
                return parts[1].strip().strip('"').strip("'")
    raise RuntimeError("Could not find __version__ in __init__.py")


def get_inno_setup_path():
    """Find iscc.exe (Inno Setup compiler) on the system."""
    candidates = [
        Path(os.environ.get("ProgramFiles(x86)", "C:/Program Files (x86)")) / "Inno Setup 6" / "ISCC.exe",
        Path(os.environ.get("ProgramFiles", "C:/Program Files")) / "Inno Setup 6" / "ISCC.exe",
        Path("C:/ProgramData/chocolatey/bin/iscc.exe"),
    ]
    for candidate in candidates:
        if candidate.exists():
            return str(candidate)

    for dir_path in os.environ.get("PATH", "").split(os.pathsep):
        candidate = Path(dir_path) / "iscc.exe"
        if candidate.exists():
            return str(candidate)

    return None


def generate_iss(source_dir: Path, output_dir: Path, version: str) -> str:
    """
    Generate a minimal Inno Setup .iss script.

    Uses Windows-style backslash paths for ISCC compatibility.
    """
    exe_name = "tts-sidecar.exe"
    source_win = str(source_dir.resolve()).replace("/", "\\")
    output_win = str(output_dir.resolve()).replace("/", "\\")

    # Build the ISS content with explicit string concatenation to avoid
    # any unicode escape issues with backslashes in multi-line strings.
    lines = []
    lines.append("; Inno Setup script for tts-sidecar")
    lines.append("; Generated by scripts/create_installer_windows.py")
    lines.append("")
    lines.append("[Setup]")
    lines.append("AppId={{E8A1B2C3-D4F5-6789-ABCD-EF0123456789}}")
    lines.append("AppName=tts-sidecar")
    lines.append("AppVersion=" + version)
    lines.append("AppPublisher=tts-sidecar")
    lines.append("DefaultDirName={autopf}\\tts-sidecar")
    lines.append("DefaultGroupName=tts-sidecar")
    lines.append("OutputDir=" + output_win)
    lines.append("OutputBaseFilename=tts-sidecar-" + version + "-setup")
    lines.append("WizardStyle=modern")
    lines.append("PrivilegesRequired=admin")
    lines.append("ArchitecturesAllowed=x64compatible")
    lines.append("ArchitecturesInstallIn64BitMode=x64compatible")
    lines.append("")
    lines.append("[Files]")
    lines.append("Source: " + source_win + "\\*; DestDir: {app}; Flags: ignoreversion recursesubdirs createallsubdirs")
    lines.append("")
    lines.append("[Icons]")
    lines.append("Name: {group}\\tts-sidecar; Filename: {app}\\tts-sidecar.exe")
    lines.append("Name: {group}\\Uninstall tts-sidecar; Filename: {uninstallexe}")
    lines.append("Name: {autodesktop}\\tts-sidecar; Filename: {app}\\tts-sidecar.exe")
    lines.append("")
    lines.append("[Registry]")
    lines.append('Root: HKLM; Subkey: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\tts-sidecar"; ValueType: string; ValueName: "DisplayName"; ValueData: "tts-sidecar"; Flags: uninsdeletekey')
    lines.append('Root: HKLM; Subkey: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\tts-sidecar"; ValueType: string; ValueName: "UninstallString"; ValueData: "{uninstallexe}"')
    lines.append('Root: HKLM; Subkey: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\tts-sidecar"; ValueType: string; ValueName: "InstallLocation"; ValueData: "{app}"')
    lines.append('Root: HKLM; Subkey: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\tts-sidecar"; ValueType: string; ValueName: "DisplayIcon"; ValueData: "{app}\\tts-sidecar.exe"')
    lines.append('Root: HKLM; Subkey: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\tts-sidecar"; ValueType: string; ValueName: "Publisher"; ValueData: "tts-sidecar"')
    lines.append('Root: HKLM; Subkey: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\tts-sidecar"; ValueType: string; ValueName: "DisplayVersion"; ValueData: "' + version + '"')
    lines.append('Root: HKLM; Subkey: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\tts-sidecar"; ValueType: dword; ValueName: "NoModify"; ValueData: 1')
    lines.append('Root: HKLM; Subkey: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\tts-sidecar"; ValueType: dword; ValueName: "NoRepair"; ValueData: 1')
    lines.append("")
    lines.append("[Run]")
    lines.append('Filename: {app}\\tts-sidecar.exe; Description: Launch tts-sidecar; Flags: nowait postinstall skipifsilent')

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Create tts-sidecar Windows installer via Inno Setup"
    )
    parser.add_argument(
        "onedir",
        type=Path,
        help="Path to the PyInstaller --onedir output folder",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output directory for the installer (default: dist/)",
    )
    args = parser.parse_args()

    source_dir = args.onedir.resolve()
    output_dir = (args.output or source_dir.parent).resolve()

    if not source_dir.exists():
        print(f"ERROR: Source directory not found: {source_dir}", file=sys.stderr)
        sys.exit(1)

    exe_in_source = source_dir / "tts-sidecar.exe"
    if not exe_in_source.exists():
        candidates = list(source_dir.glob("*/tts-sidecar.exe")) + list(source_dir.glob("tts-sidecar.exe"))
        if candidates:
            exe_in_source = candidates[0]
        else:
            print(f"ERROR: Could not find tts-sidecar.exe in {source_dir}", file=sys.stderr)
            sys.exit(1)

    version = get_version()
    print(f"Version: {version}")
    print(f"Source: {source_dir}")
    print(f"Output: {output_dir}")

    iscc = get_inno_setup_path()
    if not iscc:
        print("ERROR: Inno Setup (iscc.exe) not found.", file=sys.stderr)
        print("Install Inno Setup 6 from: https://jrsoftware.org/isdl.php", file=sys.stderr)
        print("Or via Chocolatey: choco install innosetup -y", file=sys.stderr)
        sys.exit(1)
    print(f"ISCC: {iscc}")

    output_dir.mkdir(parents=True, exist_ok=True)

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".iss", delete=False, encoding="utf-8"
    ) as f:
        iss_path = Path(f.name)
        f.write(generate_iss(source_dir, output_dir, version))

    try:
        print("Compiling installer with Inno Setup...")
        result = subprocess.run(
            [iscc, str(iss_path)],
            capture_output=True,
            text=True,
            timeout=600,
        )
        if result.returncode != 0:
            print(f"ERROR: Inno Setup failed (exit {result.returncode})", file=sys.stderr)
            print("STDOUT:", result.stdout, file=sys.stderr)
            print("STDERR:", result.stderr, file=sys.stderr)
            sys.exit(1)

        installer_name = f"tts-sidecar-{version}-setup.exe"
        installer_path = output_dir / installer_name

        if installer_path.exists():
            size_mb = installer_path.stat().st_size / 1024 / 1024
            print(f"Installer created: {installer_path}")
            print(f"Size: {size_mb:.1f} MB")
        else:
            candidates = list(output_dir.glob("tts-sidecar-*-setup.exe"))
            if candidates:
                p = candidates[0]
                size_mb = p.stat().st_size / 1024 / 1024
                print(f"Installer created: {p}")
                print(f"Size: {size_mb:.1f} MB")
            else:
                print("WARNING: Installer file not found in output dir.", file=sys.stderr)

    finally:
        try:
            iss_path.unlink()
        except OSError:
            pass


if __name__ == "__main__":
    main()
