#!/usr/bin/env python3
"""
Genera un instalador Inno Setup para tts-sidecar Windows.

Usage:
    python scripts/create_installer_windows.py <onedir_path> [--output <output_dir>]

Example:
    python scripts/create_installer_windows.py dist/tts-sidecar
"""

import argparse
import os
import subprocess
import sys
import tempfile
from pathlib import Path

# Project root (two levels up from scripts/)
SCRIPT_DIR = Path(__file__).parent.resolve()
PROJECT_ROOT = SCRIPT_DIR.parent


def get_version():
    """Read version from src/chatterbox_tts/__init__.py."""
    init_path = PROJECT_ROOT / "src" / "chatterbox_tts" / "__init__.py"
    content = init_path.read_text(encoding="utf-8")
    for line in content.splitlines():
        line = line.strip()
        if line.startswith("__version__"):
            # Parse: __version__ = "0.1.0"
            parts = line.split("=", 1)
            if len(parts) == 2:
                version = parts[1].strip().strip('"').strip("'")
                return version
    raise RuntimeError("Could not find __version__ in __init__.py")


def get_inno_setup_path():
    """Find iscc.exe (Inno Setup compiler) on the system."""
    # Common locations
    candidates = [
        # Inno Setup 6 default install
        Path(os.environ.get("ProgramFiles", "C:/Program Files")) / "Inno Setup 6" / "ISCC.exe",
        Path(os.environ.get("ProgramFiles(x86)", "C:/Program Files (x86)")) / "Inno Setup 6" / "ISCC.exe",
        # Chocolatey installs here
        Path("C:/ProgramData/chocolatey/bin/iscc.exe"),
        # On PATH
        Path("ISCC.exe"),
    ]
    for candidate in candidates:
        if candidate.exists():
            return str(candidate)

    # Try to find via PATH
    for dir_path in os.environ.get("PATH", "").split(os.pathsep):
        candidate = Path(dir_path) / "iscc.exe"
        if candidate.exists():
            return str(candidate)

    return None


def generate_iss(source_dir: Path, output_dir: Path, version: str):
    """Generate a minimal Inno Setup .iss script."""

    # The tts-sidecar onedir contains: tts-sidecar/ directory with the exe inside
    # We want the installer to extract into {pf}\tts-sidecar\
    # The .exe is at: source_dir/tts-sidecar.exe
    exe_name = "tts-sidecar.exe"

    iss_content = f"""\
; Inno Setup script for tts-sidecar v{version}
; Generated by scripts/create_installer_windows.py

#define MyAppName "tts-sidecar"
#define MyAppVersion "{version}"
#define MyAppPublisher "tts-sidecar"
#define MyAppExeName "{exe_name}"

[Setup]
AppId={{E8A1B2C3-D4F5-6789-ABCD-EF0123456789}}
AppName={{#MyAppName}}
AppVersion={{#MyAppVersion}}
AppPublisher={{#MyAppPublisher}}
DefaultDirName={{autopf}}\\{{#MyAppName}}
DefaultGroupName={{#MyAppName}}
OutputDir={output_dir.as_posix().replace(os.environ.get('TEMP', ''), '{{tmp}}').replace(os.environ.get('TMP', ''), '{{tmp}}')}
OutputBaseFilename=tts-sidecar-{{#MyAppVersion}}-setup
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

[Languages]
Name: "spanish"; MessagesFile: "compiler:Languages\\Spanish.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{{cm:CreateDesktopIcon}}"; GroupDescription: "{{cm:AdditionalIcons}}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{{cm:CreateQuickLaunchIcon}}"; GroupDescription: "{{cm:AdditionalIcons}}"; Flags: unchecked; OnlyBelowVersion: 6.1; Check: not IsAdminInstallMode

[Files]
; Copy everything from the onedir folder
Source: "{source_dir.as_posix()}\\*"; DestDir: "{{app}}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{{group}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"
Name: "{{group}}\\{{cm:UninstallProgram,{{#MyAppName}}}}"; Filename: "{{uninstallexe}}"
Name: "{{autodesktop}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"; Tasks: desktopicon
Name: "{{userappdata}}\\Microsoft\\Internet Explorer\\Quick Launch\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"; Tasks: quicklaunchicon

[Registry]
; Add/Remove Programs entry (64-bit)
RootView64: HKLM; Subkey: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{{#MyAppName}}"; ValueType: string; ValueName: "DisplayName"; ValueData: "{{#MyAppName}}"; Flags: uninsdeletekey
RootView64: HKLM; Subkey: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{{#MyAppName}}"; ValueType: string; ValueName: "UninstallString"; ValueData: '"{{uninstallexe}}"'
RootView64: HKLM; Subkey: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{{#MyAppName}}"; ValueType: string; ValueName: "InstallLocation"; ValueData: "{{app}}"
RootView64: HKLM; Subkey: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{{#MyAppName}}"; ValueType: string; ValueName: "DisplayIcon"; ValueData: "{{app}}\\{{#MyAppExeName}}"
RootView64: HKLM; Subkey: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{{#MyAppName}}"; ValueType: string; ValueName: "Publisher"; ValueData: "{{#MyAppPublisher}}"
RootView64: HKLM; Subkey: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{{#MyAppName}}"; ValueType: string; ValueName: "DisplayVersion"; ValueData: "{{#MyAppVersion}}"
RootView64: HKLM; Subkey: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{{#MyAppName}}"; ValueType: dword; ValueName: "NoModify"; ValueData: 1
RootView64: HKLM; Subkey: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{{#MyAppName}}"; ValueType: dword; ValueName: "NoRepair"; ValueData: 1

[Run]
Filename: "{{app}}\\{{#MyAppExeName}}"; Description: "{{cm:LaunchProgram,{{#StringChange(MyAppName)}}}}"; Flags: nowait postinstall skipifsilent

[Code]
// Workaround: ISCC uses {tmp} for the output dir in the .iss file,
// but we pass the real output_dir. Just write to a temp file.
"""

    return iss_content


def main():
    parser = argparse.ArgumentParser(description="Create tts-sidecar Windows installer via Inno Setup")
    parser.add_argument("onedir", type=Path, help="Path to the PyInstaller --onedir output folder")
    parser.add_argument("--output", type=Path, default=PROJECT_ROOT / "dist", help="Output directory for the installer (default: dist/)")
    args = parser.parse_args()

    source_dir = args.onedir.resolve()
    output_dir = args.output.resolve()

    if not source_dir.exists():
        print(f"ERROR: Source directory not found: {source_dir}", file=sys.stderr)
        sys.exit(1)

    # Find the exe inside the onedir folder
    # The onedir structure is: onedir/tts-sidecar.exe + _internal/
    # So source_dir should point to the "tts-sidecar" folder created by --name tts-sidecar
    # But it could also be passed as the parent dist/ folder
    # Normalize: if source_dir/tts-sidecar.exe exists, use it directly
    # if source_dir/*.exe exists, that's the root
    exe_in_source = source_dir / "tts-sidecar.exe"
    if not exe_in_source.exists():
        # Maybe the user passed the parent dist/ folder
        candidates = list(source_dir.glob("*/tts-sidecar.exe")) + list(source_dir.glob("tts-sidecar.exe"))
        if candidates:
            exe_in_source = candidates[0]
        else:
            print(f"ERROR: Could not find tts-sidecar.exe in {source_dir}", file=sys.stderr)
            sys.exit(1)

    version = get_version()
    print(f"Version: {version}")
    print(f"Source: {source_dir}")
    print(f"Output: {output_dir}")

    # Find Inno Setup
    iscc = get_inno_setup_path()
    if not iscc:
        print("ERROR: Inno Setup (iscc.exe) not found.", file=sys.stderr)
        print("Install Inno Setup 6 from: https://jrsoftware.org/isdl.php", file=sys.stderr)
        print("Or via Chocolatey: choco install innosetup -y", file=sys.stderr)
        sys.exit(1)
    print(f"ISCC: {iscc}")

    output_dir.mkdir(parents=True, exist_ok=True)

    # Generate .iss in temp dir (Inno Setup writes some temp files)
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".iss", delete=False, encoding="utf-8"
    ) as f:
        iss_path = Path(f.name)
        # For the iss file, SourceDir must use absolute path or be relative to iss location
        # We place the iss in the source_dir so relative paths work
        iss_content = generate_iss(source_dir, output_dir, version)
        f.write(iss_content)

    try:
        print(f"Compiling installer with Inno Setup...")
        result = subprocess.run(
            [iscc, str(iss_path)],
            capture_output=True,
            text=True,
            timeout=300,  # 5 min max
        )
        if result.returncode != 0:
            print(f"ERROR: Inno Setup failed (exit {result.returncode})", file=sys.stderr)
            print("STDOUT:", result.stdout, file=sys.stderr)
            print("STDERR:", result.stderr, file=sys.stderr)
            sys.exit(1)

        # Find the generated installer
        installer_name = f"tts-sidecar-{version}-setup.exe"
        installer_path = output_dir / installer_name

        # Inno Setup outputs to OutputDir; if that's a relative path in the iss,
        # it resolves relative to the .iss file location.
        # Our output_dir is absolute, so let's look there.
        if installer_path.exists():
            size_mb = installer_path.stat().st_size / 1024 / 1024
            print(f"Installer created: {installer_path}")
            print(f"Size: {size_mb:.1f} MB")
        else:
            # Fallback: search in output_dir
            candidates = list(output_dir.glob("tts-sidecar-*-setup.exe"))
            if candidates:
                p = candidates[0]
                size_mb = p.stat().st_size / 1024 / 1024
                print(f"Installer created: {p}")
                print(f"Size: {size_mb:.1f} MB")
            else:
                print("WARNING: Installer file not found in output dir.", file=sys.stderr)
                print("Check Inno Setup output above for details.")

    finally:
        # Clean up temp .iss
        try:
            iss_path.unlink()
        except OSError:
            pass


if __name__ == "__main__":
    main()
